language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  app: hidden-sierra-72238
  api_key:
    secure: XjqW5Q3CVk5qXh64SETCFvbtS5O9Gb3bH20WexxxheY33yK476b/4MmHzU7n0Kp4fgdPifk1Cp32oM/6AMHoHKGJGJVolDfVkHpWivh8j+TSODZ7Bj6rbI6tQxyhSTAHqc/J80lLO32xOoNS47hJtDTGuQY/kN6YU2fkMsYBQ4bMk0zqeOb9MzBhVYHy08VDR1zwVL0tJU1ZADER2fZF7fhqA9igUo8gPzwAmUpdWo9kgcB4c3NYu5a5VdmlQ1abdU1K2KuSj4W+O+fywQ/3kbpMdcIAGdWX9r3sgdwHBvSp39i6i9L0mW0b3SnfkYblAmiY9Y9DzLdpxhgHoSh1xcI/zF0jFXtpx9P8j6TXYLT/LT6eZ6SS66YzfZPX9dUxit+kTZ9cgPrAqnqAqcthUfNDGPsMofFPqL5cri0SW2TEX40qDzGO0+oH5cvL8T6hRfcdvyEdCtc821mUYR5c937Di2r1MSrJA2gMCHO++vis4gq6hyxXzf0BFtEaUg6EmhRfEWh6JXxdNVR2lP1JU5B3j8fNvaON62VlQp5aBly8ywzCoAY3ph3jUZXTHHC6JOGV+E+71RTfG9pxN2mXpsWYHkyHjH6pKtwteXfdERe+PVroa7xDBJgK5rZZrFSb6RyKbBmRYhVnFk+LyRKKNp9UEtGUxidWrS9wwfAT2Pg=
